2024-12-16 20:46:19,092:DEBUG:discord.client: on_ready has successfully been registered as an event
2024-12-16 20:46:19,093:INFO:discord.client: logging in using static token
2024-12-16 20:46:19,422:DEBUG:discord.http: GET https://discord.com/api/v10/users/@me with None has returned 200
2024-12-16 20:46:19,423:DEBUG:discord.http: GET /users/@me has found its initial rate limit bucket hash (78bb8553d9352a5a2f89f9def401287a).
2024-12-16 20:46:19,423:DEBUG:discord.http: GET https://discord.com/api/v10/users/@me has received {'id': '1318114372438196328', 'username': '봇물', 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104', 'discriminator': '8623', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None, 'mfa_enabled': False, 'locale': 'en-US', 'premium_type': 0, 'email': None, 'verified': True, 'bio': ''}
2024-12-16 20:46:19,877:DEBUG:discord.http: GET https://discord.com/api/v10/oauth2/applications/@me with None has returned 200
2024-12-16 20:46:19,877:DEBUG:discord.http: GET /oauth2/applications/@me has found its initial rate limit bucket hash (d28a133af187e91d71d96a223467ce49).
2024-12-16 20:46:19,877:DEBUG:discord.http: GET https://discord.com/api/v10/oauth2/applications/@me has received {'id': '1318114372438196328', 'name': '봇물', 'icon': '9ff8c4ee21b38b9f40f4169489ad4104', 'description': '', 'type': None, 'bot': {'id': '1318114372438196328', 'username': '봇물', 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104', 'discriminator': '8623', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'summary': '', 'is_monetized': False, 'is_verified': False, 'is_discoverable': False, 'bot_public': True, 'bot_require_code_grant': False, 'install_params': {'scopes': ['applications.commands'], 'permissions': '0'}, 'integration_types_config': {'0': {'oauth2_install_params': {'scopes': ['applications.commands'], 'permissions': '0'}}, '1': {'oauth2_install_params': {'scopes': ['applications.commands'], 'permissions': '0'}}}, 'verify_key': 'f4c85066c804b4edbc1d729dff543292507a1b8350c2bb3701e4cd97ed9793c6', 'flags': 565248, 'hook': True, 'storefront_available': False, 'redirect_uris': [], 'interactions_endpoint_url': None, 'role_connections_verification_url': None, 'owner': {'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': 0, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': '#000000', 'clan': None, 'primary_guild': None}, 'approximate_guild_count': 1, 'approximate_user_install_count': 0, 'interactions_event_types': [], 'interactions_version': 1, 'explicit_content_filter': 0, 'rpc_application_state': 0, 'store_application_state': 1, 'verification_state': 1, 'integration_public': True, 'integration_require_code_grant': False, 'discoverability_state': 1, 'discovery_eligibility_flags': 224, 'monetization_state': 1, 'verification_eligibility_flags': 91036, 'monetization_eligibility_flags': 181988, 'team': None, 'internal_guild_restriction': 2}
2024-12-16 20:46:20,158:DEBUG:discord.gateway: Created websocket connected to wss://gateway.discord.gg/
2024-12-16 20:46:20,159:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-7b9h",{"micros":0.0}]']}}
2024-12-16 20:46:20,160:DEBUG:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-12-16 20:46:20,356:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:46:20,468:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'READY', 's': 1, 'op': 0, 'd': {'v': 10, 'user_settings': {}, 'user': {'verified': True, 'username': '봇물', 'primary_guild': None, 'mfa_enabled': False, 'id': '1318114372438196328', 'global_name': None, 'flags': 0, 'email': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'session_type': 'normal', 'session_id': '0c6a1229d4a1df0c481b5ac6d8933406', 'resume_gateway_url': 'wss://gateway-us-east1-b.discord.gg', 'relationships': [], 'private_channels': [], 'presences': [], 'guilds': [{'unavailable': True, 'id': '1195620522294247494'}], 'guild_join_requests': [], 'geo_ordered_rtc_regions': ['south-korea', 'japan', 'hongkong', 'singapore', 'india'], 'game_relationships': [], 'auth': {}, 'application': {'id': '1318114372438196328', 'flags': 565248}, '_trace': ['["gateway-prd-us-east1-b-7b9h",{"micros":110111,"calls":["id_created",{"micros":602,"calls":[]},"session_lookup_time",{"micros":5591,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-1-238",{"micros":103570,"calls":["start_session",{"micros":42840,"calls":["discord-api-rpc-fbd795bc-h5g4m",{"micros":39297,"calls":["get_user",{"micros":4574},"get_guilds",{"micros":10118},"send_scheduled_deletion_message",{"micros":8},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":7}]}]},"starting_guild_connect",{"micros":78,"calls":[]},"presence_started",{"micros":16230,"calls":[]},"guilds_started",{"micros":72,"calls":[]},"lobbies_started",{"micros":0,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":44304,"calls":[]},"connect_finished",{"micros":44310,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":19,"calls":[]},"optimize_ready",{"micros":1,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']}}
2024-12-16 20:46:20,469:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:20,470:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0c6a1229d4a1df0c481b5ac6d8933406).
2024-12-16 20:46:20,470:DEBUG:discord.client: Dispatching event connect
2024-12-16 20:46:20,474:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'max_video_channel_users': 25, 'unavailable': False, 'application_command_counts': {}, 'mfa_level': 0, 'system_channel_flags': 15, 'vanity_url_code': None, 'banner': None, 'member_count': 25, 'rules_channel_id': '1195620849781317743', 'max_stage_video_channel_users': 50, 'default_message_notifications': 1, 'presences': [], 'discovery_splash': None, 'channels': [{'version': 1710736814791, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '2048', 'allow': '0'}], 'parent_id': '1195639935630311484', 'nsfw': False, 'name': '😀ㅣ어서와', 'last_message_id': '1318115221361004557', 'id': '1195620692620750848', 'flags': 0}, {'version': 1705133194366, 'type': 4, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'name': '공지', 'id': '1195620749151584336', 'flags': 0}, {'version': 1710736822028, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'parent_id': '1195620749151584336', 'nsfw': False, 'name': '📌ㅣ고정공지', 'last_message_id': '1195643981229465650', 'id': '1195620849781317743', 'flags': 0}, {'version': 1710736829169, 'type': 5, 'topic': '', 'rate_limit_per_user': 0, 'position': 2, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'parent_id': '1195620749151584336', 'nsfw': False, 'name': '📢ㅣ공지사항', 'last_message_id': '1266040161586647222', 'id': '1195620925589164032', 'flags': 0}, {'version': 1705133194375, 'type': 4, 'position': 2, 'permission_overwrites': [], 'name': '명령어', 'id': '1195621021991059507', 'flags': 0}, {'version': 1710736841958, 'type': 0, 'topic': '원하는 노래의 제목만 입력하면 됩니다.', 'rate_limit_per_user': 0, 'position': 4, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🐶ㅣ뽀삐', 'last_message_id': '1260524443751551056', 'id': '1195621251901829120', 'flags': 0}, {'version': 1710736847674, 'type': 0, 'topic': '마이크 못 쓰는 친구들을 위한 TTS봇', 'rate_limit_per_user': 0, 'position': 5, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🎤ㅣtts', 'last_pin_timestamp': '2024-01-13T07:48:44+00:00', 'last_message_id': '1308177657728466985', 'id': '1195621288891383808', 'flags': 0}, {'version': 1705133194388, 'type': 4, 'position': 3, 'permission_overwrites': [], 'name': '소통', 'id': '1195621329240600576', 'flags': 0}, {'version': 1710736854381, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 6, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '💬ㅣ전체채팅', 'last_pin_timestamp': '2024-11-28T03:25:41+00:00', 'last_message_id': '1318179611225493544', 'id': '1195621469682683944', 'flags': 0}, {'version': 1710736868656, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 8, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📚ㅣ정보공유', 'last_pin_timestamp': '2024-01-13T08:26:13+00:00', 'last_message_id': '1315890412485087282', 'id': '1195621924445896745', 'flags': 0}, {'version': 1722982677867, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '🔊ㅣ전체보이스', 'last_message_id': '1284874571228381386', 'id': '1195622348494221384', 'flags': 0, 'bitrate': 96000}, {'version': 1710736906253, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '🔊ㅣ수다떨기', 'last_message_id': '1244781625531830343', 'id': '1195622422745993257', 'flags': 0, 'bitrate': 64000}, {'version': 1705303052774, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 2, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'name': '😴ㆍ잠수방', 'last_message_id': '1244781627175866388', 'id': '1195622458816987146', 'flags': 0, 'bitrate': 64000}, {'version': 1705133194403, 'type': 4, 'position': 4, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'name': '서버관리', 'id': '1195624790858408048', 'flags': 0}, {'version': 1710737189370, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 12, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'parent_id': '1195624790858408048', 'nsfw': False, 'name': '💾ㅣ채팅로그', 'last_message_id': '1318182286935592972', 'id': '1195624958257266749', 'flags': 0}, {'version': 1710737182373, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 11, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'parent_id': '1195624790858408048', 'nsfw': False, 'name': '💻ㅣ관리자', 'last_message_id': '1314097655248322593', 'id': '1195625084883325069', 'flags': 0}, {'version': 1710736835389, 'type': 0, 'topic': '⏹ - 재생을 멈추고, 대기열을 초기화해요.\n🔁 - 반복 모드를 변경해요.\n🔀 - 대기열에 있는 트랙을 섞어요.\n⏭ - 재생 중인 노래를 스킵해요.\n⏯ - 곡을 일시정지하거나 재생해요.', 'rate_limit_per_user': 0, 'position': 3, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🍭ㅣ하리보', 'last_pin_timestamp': '2024-01-13T07:57:56+00:00', 'last_message_id': '1260524456988639243', 'id': '1195637508709568562', 'flags': 0}, {'version': 1705134571662, 'type': 4, 'position': 0, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '2048', 'allow': '0'}], 'name': '환영', 'id': '1195639935630311484', 'flags': 0}, {'version': 1710736883090, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 10, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📬ㅣ건의함', 'last_pin_timestamp': '2024-01-13T08:07:51+00:00', 'last_message_id': '1314489183741542411', 'id': '1195640167982190592', 'flags': 0}, {'version': 1710736862476, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 7, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📷ㅣ짤방', 'last_pin_timestamp': '2024-01-23T00:47:05+00:00', 'last_message_id': '1318171183400747110', 'id': '1199152735480713267', 'flags': 0}, {'version': 1725002828909, 'type': 15, 'topic': '||궁금한 것들이 있다면 이곳에||', 'theme_color': None, 'template': '', 'rate_limit_per_user': 10, 'position': 9, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '0', 'allow': '65536'}], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '❓ㅣ질문방', 'last_message_id': '1301509790693851136', 'id': '1199156871869775923', 'icon_emoji': None, 'flags': 16, 'default_sort_order': None, 'default_reaction_emoji': {'emoji_name': '👍', 'emoji_id': None}, 'default_forum_layout': 1, 'available_tags': [{'name': '해결필요', 'moderated': False, 'id': '1199157208353615893', 'emoji_name': '✏️', 'emoji_id': None}, {'name': '해결완료', 'moderated': False, 'id': '1199157313370599485', 'emoji_name': '✅', 'emoji_id': None}, {'name': '해결불가', 'moderated': False, 'id': '1199157362422988821', 'emoji_name': '❌', 'emoji_id': None}]}, {'version': 1734338701781, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 13, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '💧ㅣ봇물', 'last_message_id': '1318182285316587550', 'id': '1318136795229061120', 'flags': 0}], 'premium_tier': 0, 'id': '1195620522294247494', 'icon': 'a57fb06f70c17a29e5822f08229f24da', 'activity_instances': [], 'public_updates_channel_id': '1195625084883325069', 'incidents_data': {'raid_detected_at': '2024-12-05T05:14:55.709010+00:00', 'invites_disabled_until': None, 'dms_disabled_until': None, 'dm_spam_detected_at': None}, 'inventory_settings': None, 'embedded_activities': [], 'clan': None, 'afk_channel_id': '1195622458816987146', 'emojis': [], 'max_members': 500000, 'name': '최강', 'preferred_locale': 'ko', 'nsfw_level': 0, 'nsfw': False, 'explicit_content_filter': 2, 'threads': [{'type': 11, 'total_message_sent': 8, 'thread_metadata': {'locked': False, 'create_timestamp': '2024-11-28T03:03:18.472960+00:00', 'auto_archive_duration': 4320, 'archived': False, 'archive_timestamp': '2024-11-28T03:03:18.472960+00:00'}, 'rate_limit_per_user': 0, 'parent_id': '1195621469682683944', 'owner_id': '846325069994000424', 'name': 'ucc 조별로 치킨(양념, 후라이드), 피자종류 골라서 팀 대표가 올려', 'message_count': 7, 'member_count': 1, 'last_message_id': '1311534784518033529', 'id': '1311527458998059050', 'guild_id': '1195620522294247494', 'flags': 0}, {'type': 11, 'total_message_sent': 18, 'thread_metadata': {'locked': False, 'create_timestamp': '2024-12-06T06:31:37.411910+00:00', 'auto_archive_duration': 4320, 'archived': False, 'archive_timestamp': '2024-12-06T06:31:37.411910+00:00'}, 'rate_limit_per_user': 0, 'parent_id': '1195640167982190592', 'owner_id': '846325069994000424', 'name': '스타 박아**줘** (스레드 열어주세요) @준준', 'message_count': 18, 'member_count': 10, 'last_message_id': '1315632819950583958', 'id': '1314479239403409478', 'guild_id': '1195620522294247494', 'flags': 0}], 'region': 'deprecated', 'members': [{'user': {'username': '봇물', 'public_flags': 0, 'id': '1318114372438196328', 'global_name': None, 'display_name': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'roles': ['1195629770281582602', '1318115220325138445'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}], 'large': False, 'description': None, 'features': ['COMMUNITY', 'SOUNDBOARD', 'NEWS'], 'application_id': None, 'stickers': [{'version': 1705299422099, 'type': 2, 'tags': '🏫', 'name': 'GSM', 'id': '1196337228293603348', 'guild_id': '1195620522294247494', 'format_type': 1, 'description': '', 'available': True, 'asset': ''}], 'safety_alerts_channel_id': '1195625084883325069', 'soundboard_sounds': [], 'afk_timeout': 1800, 'premium_progress_bar_enabled': False, 'owner_id': '846325069994000424', 'hub_type': None, 'splash': None, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'premium_subscription_count': 0, 'system_channel_id': '1195620692620750848', 'home_header': None, 'roles': [{'version': 1733375534712, 'unicode_emoji': None, 'tags': {}, 'position': 0, 'permissions': '2222085186767425', 'name': '@everyone', 'mentionable': False, 'managed': False, 'id': '1195620522294247494', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834611, 'unicode_emoji': None, 'tags': {}, 'position': 5, 'permissions': '8', 'name': '서버 관리자', 'mentionable': False, 'managed': False, 'id': '1195622998825242694', 'icon': None, 'hoist': False, 'flags': 0, 'color': 3447003}, {'version': 1733375617678, 'unicode_emoji': None, 'tags': {}, 'position': 3, 'permissions': '1024', 'name': 'GSM', 'mentionable': False, 'managed': False, 'id': '1195623696895852564', 'icon': None, 'hoist': False, 'flags': 0, 'color': 7602064}, {'version': 1731652834623, 'unicode_emoji': None, 'tags': {'bot_id': '159985870458322944'}, 'position': 10, 'permissions': '364870364383', 'name': 'MEE6', 'mentionable': False, 'managed': True, 'id': '1195629722185506940', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834609, 'unicode_emoji': None, 'tags': {}, 'position': 4, 'permissions': '8', 'name': '봇', 'mentionable': False, 'managed': False, 'id': '1195629770281582602', 'icon': None, 'hoist': True, 'flags': 0, 'color': 5896959}, {'version': 1731652834619, 'unicode_emoji': None, 'tags': {'bot_id': '513423712582762502'}, 'position': 8, 'permissions': '36719617', 'name': 'TTS Bot!', 'mentionable': False, 'managed': True, 'id': '1195632271760302105', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834617, 'unicode_emoji': None, 'tags': {'bot_id': '479108435984515072'}, 'position': 7, 'permissions': '431689690192', 'name': '노래하는 하리보', 'mentionable': False, 'managed': True, 'id': '1195635742307786814', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834613, 'unicode_emoji': None, 'tags': {'bot_id': '896270994740764684'}, 'position': 6, 'permissions': '281357446256', 'name': '뽀삐', 'mentionable': False, 'managed': True, 'id': '1195638311868444835', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834621, 'unicode_emoji': None, 'tags': {'bot_id': '155149108183695360'}, 'position': 9, 'permissions': '1513962695871', 'name': 'Dyno', 'mentionable': False, 'managed': True, 'id': '1195638871187275878', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731761636512, 'unicode_emoji': None, 'tags': {'premium_subscriber': None}, 'position': 1, 'permissions': '2221707229646401', 'name': '흑우', 'mentionable': False, 'managed': True, 'id': '1257989377561460839', 'icon': None, 'hoist': False, 'flags': 0, 'color': 16023551}, {'version': 1731761625458, 'unicode_emoji': None, 'tags': {}, 'position': 2, 'permissions': '0', 'name': '범죄자', 'mentionable': False, 'managed': False, 'id': '1306871368276770908', 'icon': None, 'hoist': False, 'flags': 0, 'color': 16711680}, {'version': 1734333557995, 'unicode_emoji': None, 'tags': {'bot_id': '1318114372438196328'}, 'position': 1, 'permissions': '8', 'name': '8G4B-bot', 'mentionable': False, 'managed': True, 'id': '1318115220325138445', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}], 'version': 1733375695710, 'latest_onboarding_question_id': None, 'verification_level': 1, 'guild_scheduled_events': [], 'voice_states': [], 'lazy': True, 'stage_instances': []}}
2024-12-16 20:46:20,483:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:20,485:DEBUG:discord.client: Dispatching event guild_available
2024-12-16 20:46:22,494:DEBUG:discord.client: Dispatching event ready
2024-12-16 20:46:23,972:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 3, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:23.811000+00:00', 'pinned': False, 'nonce': '1318182437284478976', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182437775347745', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!안녕', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:23,976:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:23,976:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:23,977:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:24,280:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182437775347745 with None has returned 204
2024-12-16 20:46:24,281:DEBUG:discord.http: DELETE /channels/{channel_id}/messages/{message_id}:sub-10-seconds has found its initial rate limit bucket hash (3df15bae86f6647dd4dfcbd5c6949480).
2024-12-16 20:46:24,281:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182437775347745 has received 
2024-12-16 20:46:24,307:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_DELETE', 's': 4, 'op': 0, 'd': {'id': '1318182437775347745', 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:24,307:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:24,308:DEBUG:discord.client: Dispatching event raw_message_delete
2024-12-16 20:46:24,308:DEBUG:discord.client: Dispatching event message_delete
2024-12-16 20:46:24,403:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 5, 'op': 0, 'd': {'webhook_id': '1195639797226680372', 'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:24.314000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182439885078579', 'flags': 0, 'embeds': [{'type': 'rich', 'timestamp': '2024-12-16T11:46:24.211000+00:00', 'footer': {'text': 'Author: 488944260624678912 | Message ID: 1318182437775347745'}, 'description': '**Message sent by <@488944260624678912> Deleted in <#1318136795229061120>**\n!안녕', 'color': 16729871, 'author': {'proxy_icon_url': 'https://images-ext-1.discordapp.net/external/vKRRoJ8wHd-lZK9bNYLimmEa98s-u1SVOEG3dpmulww/%3Fsize%3D4096/https/cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png', 'name': 'haensol', 'icon_url': 'https://cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png?size=4096'}}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1195624958257266749', 'author': {'username': 'Dyno', 'id': '1195639797226680372', 'global_name': None, 'discriminator': '0000', 'bot': True, 'avatar': 'a06062af9b11085ab715e340deaab267'}, 'attachments': [], 'application_id': '161660517914509312', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:24,406:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:24,406:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:24,593:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":3447003,"type":"rich","title":"\uc548\ub155!"}],"content":"<@488944260624678912>","components":[],"message_reference":{"message_id":1318182437775347745,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 400
2024-12-16 20:46:24,596:DEBUG:discord.http: POST /channels/{channel_id}/messages has found its initial rate limit bucket hash (3df15bae86f6647dd4dfcbd5c6949480).
2024-12-16 20:46:24,596:DEBUG:discord.client: Dispatching event command_error
2024-12-16 20:46:24,597:ERROR:discord.ext.commands.bot: Ignoring exception in command 안녕
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\OneDrive\문서\programming\파이썬\bot\commands\Greeting.py", line 23, in greet
    await ctx.reply(f"{ctx.author.mention}", embed=embed)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 746, in reply
    return await self.send(content, reference=self.message, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 1039, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1618, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 758, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
2024-12-16 20:46:26,848:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'TYPING_START', 's': 6, 'op': 0, 'd': {'user_id': '488944260624678912', 'timestamp': 1734349586, 'member': {'user': {'username': 'haensol', 'public_flags': 64, 'id': '488944260624678912', 'global_name': '재욱', 'display_name': '재욱', 'discriminator': '0', 'clan': None, 'bot': False, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:26,852:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:26,853:DEBUG:discord.client: Dispatching event typing
2024-12-16 20:46:26,853:DEBUG:discord.client: Dispatching event raw_typing
2024-12-16 20:46:27,092:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 7, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:26.988000+00:00', 'pinned': False, 'nonce': '1318182450060328960', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182451100782654', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.아침', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:27,093:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:27,093:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:27,094:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:27,722:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 8, 'op': 0, 'd': {'type': 19, 'tts': False, 'timestamp': '2024-12-16T11:46:27.632000+00:00', 'referenced_message': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:26.988000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182451100782654', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.아침', 'components': [], 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': []}, 'pinned': False, 'message_reference': {'type': 0, 'message_id': '1318182451100782654', 'guild_id': '1195620522294247494', 'channel_id': '1318136795229061120'}, 'mentions': [{'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195629770281582602', '1318115220325138445'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182453801910312', 'flags': 0, 'embeds': [{'type': 'rich', 'title': '아침', 'description': '백미밥 \n참치김치찌개 (5.9)\n닭고기메추리알조림 (1.5.6.13.15)\n깻잎찜/ (5.6.13)\n깍두기 (9)\n김구이 \n모닝시리얼우유 (2)\n수제찰보리영양빵 (1.2.5.6)', 'content_scan_version': 0, 'color': 10181046}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': '봇물', 'public_flags': 0, 'primary_guild': None, 'id': '1318114372438196328', 'global_name': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:27,724:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:27,725:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:27,751:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":10181046,"type":"rich","description":"\ubc31\ubbf8\ubc25 \n\ucc38\uce58\uae40\uce58\ucc0c\uac1c (5.9)\n\ub2ed\uace0\uae30\uba54\ucd94\ub9ac\uc54c\uc870\ub9bc (1.5.6.13.15)\n\uae7b\uc78e\ucc1c/ (5.6.13)\n\uae4d\ub450\uae30 (9)\n\uae40\uad6c\uc774 \n\ubaa8\ub2dd\uc2dc\ub9ac\uc5bc\uc6b0\uc720 (2)\n\uc218\uc81c\ucc30\ubcf4\ub9ac\uc601\uc591\ube75 (1.2.5.6)","title":"\uc544\uce68"}],"content":null,"components":[],"message_reference":{"message_id":1318182451100782654,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 200
2024-12-16 20:46:27,759:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages has received {'type': 19, 'content': '', 'mentions': [{'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': 0, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': '#000000', 'clan': None, 'primary_guild': None}], 'mention_roles': [], 'attachments': [], 'embeds': [{'type': 'rich', 'title': '아침', 'description': '백미밥 \n참치김치찌개 (5.9)\n닭고기메추리알조림 (1.5.6.13.15)\n깻잎찜/ (5.6.13)\n깍두기 (9)\n김구이 \n모닝시리얼우유 (2)\n수제찰보리영양빵 (1.2.5.6)', 'color': 10181046, 'content_scan_version': 0}], 'timestamp': '2024-12-16T11:46:27.632000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182453801910312', 'channel_id': '1318136795229061120', 'author': {'id': '1318114372438196328', 'username': '봇물', 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104', 'discriminator': '8623', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False, 'message_reference': {'type': 0, 'channel_id': '1318136795229061120', 'message_id': '1318182451100782654', 'guild_id': '1195620522294247494'}, 'referenced_message': {'type': 0, 'content': '!급식.아침', 'mentions': [], 'mention_roles': [], 'attachments': [], 'embeds': [], 'timestamp': '2024-12-16T11:46:26.988000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182451100782654', 'channel_id': '1318136795229061120', 'author': {'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': None, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False}}
2024-12-16 20:46:27,762:DEBUG:discord.client: Dispatching event command_completion
2024-12-16 20:46:30,173:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 9, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:30.024000+00:00', 'pinned': False, 'nonce': '1318182463385632768', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182463834685441', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.점심', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:30,174:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:30,175:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:30,175:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:30,816:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 10, 'op': 0, 'd': {'type': 19, 'tts': False, 'timestamp': '2024-12-16T11:46:30.616000+00:00', 'referenced_message': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:30.024000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182463834685441', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.점심', 'components': [], 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': []}, 'pinned': False, 'message_reference': {'type': 0, 'message_id': '1318182463834685441', 'guild_id': '1195620522294247494', 'channel_id': '1318136795229061120'}, 'mentions': [{'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195629770281582602', '1318115220325138445'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182466317451276', 'flags': 0, 'embeds': [{'type': 'rich', 'title': '점심', 'description': '혼합잡곡밥 (5)\n바지락칼국수 (6.9.18)\n파채겉절이 (5.6.13)\n새우탱글가마보꼬지짐 (1.5.6.9.12)\n갈비구운떡말이 (5.6.10.15.16.18)\n깍두기 (9)\n요구르트(닥터키즈) (2)', 'content_scan_version': 0, 'color': 10181046}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': '봇물', 'public_flags': 0, 'primary_guild': None, 'id': '1318114372438196328', 'global_name': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:30,819:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:30,820:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:30,921:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":10181046,"type":"rich","description":"\ud63c\ud569\uc7a1\uace1\ubc25 (5)\n\ubc14\uc9c0\ub77d\uce7c\uad6d\uc218 (6.9.18)\n\ud30c\ucc44\uac89\uc808\uc774 (5.6.13)\n\uc0c8\uc6b0\ud0f1\uae00\uac00\ub9c8\ubcf4\uaf2c\uc9c0\uc9d0 (1.5.6.9.12)\n\uac08\ube44\uad6c\uc6b4\ub5a1\ub9d0\uc774 (5.6.10.15.16.18)\n\uae4d\ub450\uae30 (9)\n\uc694\uad6c\ub974\ud2b8(\ub2e5\ud130\ud0a4\uc988) (2)","title":"\uc810\uc2ec"}],"content":null,"components":[],"message_reference":{"message_id":1318182463834685441,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 200
2024-12-16 20:46:30,922:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages has received {'type': 19, 'content': '', 'mentions': [{'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': 0, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': '#000000', 'clan': None, 'primary_guild': None}], 'mention_roles': [], 'attachments': [], 'embeds': [{'type': 'rich', 'title': '점심', 'description': '혼합잡곡밥 (5)\n바지락칼국수 (6.9.18)\n파채겉절이 (5.6.13)\n새우탱글가마보꼬지짐 (1.5.6.9.12)\n갈비구운떡말이 (5.6.10.15.16.18)\n깍두기 (9)\n요구르트(닥터키즈) (2)', 'color': 10181046, 'content_scan_version': 0}], 'timestamp': '2024-12-16T11:46:30.616000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182466317451276', 'channel_id': '1318136795229061120', 'author': {'id': '1318114372438196328', 'username': '봇물', 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104', 'discriminator': '8623', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False, 'message_reference': {'type': 0, 'channel_id': '1318136795229061120', 'message_id': '1318182463834685441', 'guild_id': '1195620522294247494'}, 'referenced_message': {'type': 0, 'content': '!급식.점심', 'mentions': [], 'mention_roles': [], 'attachments': [], 'embeds': [], 'timestamp': '2024-12-16T11:46:30.024000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182463834685441', 'channel_id': '1318136795229061120', 'author': {'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': None, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False}}
2024-12-16 20:46:30,926:DEBUG:discord.client: Dispatching event command_completion
2024-12-16 20:46:33,323:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'TYPING_START', 's': 11, 'op': 0, 'd': {'user_id': '488944260624678912', 'timestamp': 1734349593, 'member': {'user': {'username': 'haensol', 'public_flags': 64, 'id': '488944260624678912', 'global_name': '재욱', 'display_name': '재욱', 'discriminator': '0', 'clan': None, 'bot': False, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:33,323:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:33,324:DEBUG:discord.client: Dispatching event typing
2024-12-16 20:46:33,324:DEBUG:discord.client: Dispatching event raw_typing
2024-12-16 20:46:33,839:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 12, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:33.734000+00:00', 'pinned': False, 'nonce': '1318182478489321472', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182479395553290', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.저녁', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:33,840:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:33,841:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:33,841:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:34,532:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 13, 'op': 0, 'd': {'type': 19, 'tts': False, 'timestamp': '2024-12-16T11:46:34.387000+00:00', 'referenced_message': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:33.734000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182479395553290', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!급식.저녁', 'components': [], 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': []}, 'pinned': False, 'message_reference': {'type': 0, 'message_id': '1318182479395553290', 'guild_id': '1195620522294247494', 'channel_id': '1318136795229061120'}, 'mentions': [{'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195629770281582602', '1318115220325138445'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182482134175756', 'flags': 0, 'embeds': [{'type': 'rich', 'title': '저녁', 'description': '오리훈제김치볶음밥&김가루. (1.2.5.6.9.10.13.15.16.18)\n된장찌개(석). (5.6.9)\n숙주나물. \n계란후라이. (1.5)\n깍두기.. (9)\n콤비네이션피자. (1.2.5.6.9.10.12.13.15.16.18)\n피크닉. (13)', 'content_scan_version': 0, 'color': 10181046}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': '봇물', 'public_flags': 0, 'primary_guild': None, 'id': '1318114372438196328', 'global_name': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:34,537:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:34,538:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:34,602:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":10181046,"type":"rich","description":"\uc624\ub9ac\ud6c8\uc81c\uae40\uce58\ubcf6\uc74c\ubc25&\uae40\uac00\ub8e8. (1.2.5.6.9.10.13.15.16.18)\n\ub41c\uc7a5\ucc0c\uac1c(\uc11d). (5.6.9)\n\uc219\uc8fc\ub098\ubb3c. \n\uacc4\ub780\ud6c4\ub77c\uc774. (1.5)\n\uae4d\ub450\uae30.. (9)\n\ucf64\ube44\ub124\uc774\uc158\ud53c\uc790. (1.2.5.6.9.10.12.13.15.16.18)\n\ud53c\ud06c\ub2c9. (13)","title":"\uc800\ub141"}],"content":null,"components":[],"message_reference":{"message_id":1318182479395553290,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 200
2024-12-16 20:46:34,603:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages has received {'type': 19, 'content': '', 'mentions': [{'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': 0, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': '#000000', 'clan': None, 'primary_guild': None}], 'mention_roles': [], 'attachments': [], 'embeds': [{'type': 'rich', 'title': '저녁', 'description': '오리훈제김치볶음밥&김가루. (1.2.5.6.9.10.13.15.16.18)\n된장찌개(석). (5.6.9)\n숙주나물. \n계란후라이. (1.5)\n깍두기.. (9)\n콤비네이션피자. (1.2.5.6.9.10.12.13.15.16.18)\n피크닉. (13)', 'color': 10181046, 'content_scan_version': 0}], 'timestamp': '2024-12-16T11:46:34.387000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182482134175756', 'channel_id': '1318136795229061120', 'author': {'id': '1318114372438196328', 'username': '봇물', 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104', 'discriminator': '8623', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': None, 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False, 'message_reference': {'type': 0, 'channel_id': '1318136795229061120', 'message_id': '1318182479395553290', 'guild_id': '1195620522294247494'}, 'referenced_message': {'type': 0, 'content': '!급식.저녁', 'mentions': [], 'mention_roles': [], 'attachments': [], 'embeds': [], 'timestamp': '2024-12-16T11:46:33.734000+00:00', 'edited_timestamp': None, 'flags': 0, 'components': [], 'id': '1318182479395553290', 'channel_id': '1318136795229061120', 'author': {'id': '488944260624678912', 'username': 'haensol', 'avatar': 'ce51829a1e6e5de16343695cf9bf728e', 'discriminator': '0', 'public_flags': 64, 'flags': 64, 'banner': None, 'accent_color': None, 'global_name': '재욱', 'avatar_decoration_data': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'pinned': False, 'mention_everyone': False, 'tts': False}}
2024-12-16 20:46:34,605:DEBUG:discord.client: Dispatching event command_completion
2024-12-16 20:46:37,847:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'TYPING_START', 's': 14, 'op': 0, 'd': {'user_id': '488944260624678912', 'timestamp': 1734349597, 'member': {'user': {'username': 'haensol', 'public_flags': 64, 'id': '488944260624678912', 'global_name': '재욱', 'display_name': '재욱', 'discriminator': '0', 'clan': None, 'bot': False, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:37,848:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:37,848:DEBUG:discord.client: Dispatching event typing
2024-12-16 20:46:37,849:DEBUG:discord.client: Dispatching event raw_typing
2024-12-16 20:46:39,315:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 15, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:39.189000+00:00', 'pinned': False, 'nonce': '1318182501532827648', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182502275481601', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!도박.주사위', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:39,317:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:39,317:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:39,318:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:39,686:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182502275481601 with None has returned 204
2024-12-16 20:46:39,687:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182502275481601 has received 
2024-12-16 20:46:39,689:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_DELETE', 's': 16, 'op': 0, 'd': {'id': '1318182502275481601', 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:39,690:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:39,690:DEBUG:discord.client: Dispatching event raw_message_delete
2024-12-16 20:46:39,691:DEBUG:discord.client: Dispatching event message_delete
2024-12-16 20:46:39,818:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 17, 'op': 0, 'd': {'webhook_id': '1195639797226680372', 'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:39.718000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182504494268457', 'flags': 0, 'embeds': [{'type': 'rich', 'timestamp': '2024-12-16T11:46:39.601000+00:00', 'footer': {'text': 'Author: 488944260624678912 | Message ID: 1318182502275481601'}, 'description': '**Message sent by <@488944260624678912> Deleted in <#1318136795229061120>**\n!도박.주사위', 'color': 16729871, 'author': {'proxy_icon_url': 'https://images-ext-1.discordapp.net/external/vKRRoJ8wHd-lZK9bNYLimmEa98s-u1SVOEG3dpmulww/%3Fsize%3D4096/https/cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png', 'name': 'haensol', 'icon_url': 'https://cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png?size=4096'}}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1195624958257266749', 'author': {'username': 'Dyno', 'id': '1195639797226680372', 'global_name': None, 'discriminator': '0000', 'bot': True, 'avatar': 'a06062af9b11085ab715e340deaab267'}, 'attachments': [], 'application_id': '161660517914509312', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:39,819:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:39,819:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:39,935:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":15158332,"type":"rich","description":"**1\ubd80\ud130 6\uae4c\uc9c0 \uc22b\uc790**\ub9cc \uc785\ub825\ud574\ub77c...","title":"\uc624\ub958"}],"content":"<@488944260624678912>","components":[],"message_reference":{"message_id":1318182502275481601,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 400
2024-12-16 20:46:39,936:DEBUG:discord.client: Dispatching event command_error
2024-12-16 20:46:39,937:ERROR:discord.ext.commands.bot: Ignoring exception in command 도박.주사위
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\OneDrive\문서\programming\파이썬\bot\commands\Gambling.py", line 70, in dice
    await ctx.reply(f"{ctx.author.mention}", embed=embed)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 746, in reply
    return await self.send(content, reference=self.message, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 1039, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1618, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 758, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
2024-12-16 20:46:42,720:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'TYPING_START', 's': 18, 'op': 0, 'd': {'user_id': '488944260624678912', 'timestamp': 1734349602, 'member': {'user': {'username': 'haensol', 'public_flags': 64, 'id': '488944260624678912', 'global_name': '재욱', 'display_name': '재욱', 'discriminator': '0', 'clan': None, 'bot': False, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:42,721:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:42,721:DEBUG:discord.client: Dispatching event typing
2024-12-16 20:46:42,721:DEBUG:discord.client: Dispatching event raw_typing
2024-12-16 20:46:44,452:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 19, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:44.364000+00:00', 'pinned': False, 'nonce': '1318182523062190080', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['1195623696895852564'], 'premium_since': None, 'pending': False, 'nick': 'React.js', 'mute': False, 'joined_at': '2024-12-05T05:16:02.423000+00:00', 'flags': 1, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1318182523980877834', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!도박.주사위 0 1', 'components': [], 'channel_type': 0, 'channel_id': '1318136795229061120', 'author': {'username': 'haensol', 'public_flags': 64, 'primary_guild': None, 'id': '488944260624678912', 'global_name': '재욱', 'discriminator': '0', 'clan': None, 'avatar_decoration_data': None, 'avatar': 'ce51829a1e6e5de16343695cf9bf728e'}, 'attachments': [], 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:44,454:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:44,455:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:44,455:DEBUG:discord.client: Dispatching event command
2024-12-16 20:46:44,733:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_DELETE', 's': 20, 'op': 0, 'd': {'id': '1318182523980877834', 'channel_id': '1318136795229061120', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:44,734:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:44,734:DEBUG:discord.client: Dispatching event raw_message_delete
2024-12-16 20:46:44,735:DEBUG:discord.client: Dispatching event message_delete
2024-12-16 20:46:44,736:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182523980877834 with None has returned 204
2024-12-16 20:46:44,736:DEBUG:discord.http: DELETE https://discord.com/api/v10/channels/1318136795229061120/messages/1318182523980877834 has received 
2024-12-16 20:46:44,831:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 21, 'op': 0, 'd': {'webhook_id': '1195639797226680372', 'type': 0, 'tts': False, 'timestamp': '2024-12-16T11:46:44.739000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'id': '1318182525553606728', 'flags': 0, 'embeds': [{'type': 'rich', 'timestamp': '2024-12-16T11:46:44.668000+00:00', 'footer': {'text': 'Author: 488944260624678912 | Message ID: 1318182523980877834'}, 'description': '**Message sent by <@488944260624678912> Deleted in <#1318136795229061120>**\n!도박.주사위 0 1', 'color': 16729871, 'author': {'proxy_icon_url': 'https://images-ext-1.discordapp.net/external/vKRRoJ8wHd-lZK9bNYLimmEa98s-u1SVOEG3dpmulww/%3Fsize%3D4096/https/cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png', 'name': 'haensol', 'icon_url': 'https://cdn.discordapp.com/avatars/488944260624678912/ce51829a1e6e5de16343695cf9bf728e.png?size=4096'}}], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_type': 0, 'channel_id': '1195624958257266749', 'author': {'username': 'Dyno', 'id': '1195639797226680372', 'global_name': None, 'discriminator': '0000', 'bot': True, 'avatar': 'a06062af9b11085ab715e340deaab267'}, 'attachments': [], 'application_id': '161660517914509312', 'guild_id': '1195620522294247494'}}
2024-12-16 20:46:44,833:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 20:46:44,833:DEBUG:discord.client: Dispatching event message
2024-12-16 20:46:45,032:DEBUG:discord.http: POST https://discord.com/api/v10/channels/1318136795229061120/messages with {"embeds":[{"color":15158332,"type":"rich","description":"**1\ubd80\ud130 6\uae4c\uc9c0 \uc22b\uc790**\ub9cc \uc785\ub825\ud574\ub77c...","title":"\uc624\ub958"}],"content":"<@488944260624678912>","components":[],"message_reference":{"message_id":1318182523980877834,"channel_id":1318136795229061120,"guild_id":1195620522294247494},"tts":false} has returned 400
2024-12-16 20:46:45,033:DEBUG:discord.client: Dispatching event command_error
2024-12-16 20:46:45,035:ERROR:discord.ext.commands.bot: Ignoring exception in command 도박.주사위
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\OneDrive\문서\programming\파이썬\bot\commands\Gambling.py", line 70, in dice
    await ctx.reply(f"{ctx.author.mention}", embed=embed)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 746, in reply
    return await self.send(content, reference=self.message, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\context.py", line 1039, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1618, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 758, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
2024-12-16 20:47:01,420:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:47:01,619:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:47:42,674:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:47:42,879:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:48:23,930:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:48:24,129:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:49:05,195:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:49:05,397:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:49:46,449:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:49:46,646:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:50:27,709:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:50:27,910:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:51:08,970:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:51:09,175:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:51:50,230:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:51:50,439:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:52:31,483:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:52:31,682:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:53:12,739:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:53:12,944:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:53:53,998:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:53:54,199:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:54:35,251:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:54:35,472:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:55:16,519:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:55:16,726:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:55:57,774:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:55:58,020:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:56:39,033:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:56:39,245:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:57:20,287:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:57:20,551:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:58:01,547:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:58:01,874:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:58:42,800:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:58:43,104:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 20:59:24,064:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 20:59:24,394:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:00:05,324:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 21.
2024-12-16 21:00:10,652:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
2024-12-16 21:00:10,662:DEBUG:discord.gateway: Websocket closed with 1006, attempting a reconnect.
2024-12-16 21:00:10,662:DEBUG:discord.client: Got a request to RESUME the websocket.
2024-12-16 21:00:10,663:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:00:10,733:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:00:10,733:ERROR:discord.client: Attempting a reconnect in 1.06s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:00:11,844:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:00:11,844:ERROR:discord.client: Attempting a reconnect in 2.58s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:00:14,736:DEBUG:discord.gateway: Created websocket connected to wss://gateway-us-east1-b.discord.gg
2024-12-16 21:00:14,736:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-21s2",{"micros":0.0}]']}}
2024-12-16 21:00:14,742:DEBUG:discord.gateway: Shard ID None has sent the RESUME payload.
2024-12-16 21:00:14,954:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:00:14,954:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'RESUMED', 's': 22, 'op': 0, 'd': {'_trace': ['["gateway-prd-us-east1-b-21s2",{"micros":526,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":228,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-1-238",{"micros":25}]}]']}}
2024-12-16 21:00:14,954:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 21:00:14,954:INFO:discord.gateway: Shard ID None has successfully RESUMED session 0c6a1229d4a1df0c481b5ac6d8933406.
2024-12-16 21:00:14,958:DEBUG:discord.client: Dispatching event resumed
2024-12-16 21:00:55,997:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:00:56,196:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:01:37,252:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:01:37,453:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:02:18,518:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:02:18,824:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:02:59,778:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:02:59,983:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:03:41,038:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:03:41,359:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:04:22,293:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:04:22,492:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:05:03,555:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:05:03,896:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:05:44,807:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:05:45,054:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:06:26,073:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:06:26,324:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:07:07,324:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:07:07,589:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:07:48,579:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:07:48,855:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:08:29,845:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:08:30,282:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:09:11,104:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 22.
2024-12-16 21:09:30,274:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
2024-12-16 21:09:30,276:DEBUG:discord.gateway: Websocket closed with 1006, attempting a reconnect.
2024-12-16 21:09:30,276:DEBUG:discord.client: Got a request to RESUME the websocket.
2024-12-16 21:09:30,276:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:09:30,276:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:09:30,276:ERROR:discord.client: Attempting a reconnect in 4.48s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:09:34,772:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:09:34,772:ERROR:discord.client: Attempting a reconnect in 14.00s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:09:53,761:DEBUG:discord.gateway: Created websocket connected to wss://gateway-us-east1-b.discord.gg
2024-12-16 21:09:53,761:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-v7b4",{"micros":0.0}]']}}
2024-12-16 21:09:53,761:DEBUG:discord.gateway: Shard ID None has sent the RESUME payload.
2024-12-16 21:09:54,065:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:09:54,075:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'RESUMED', 's': 23, 'op': 0, 'd': {'_trace': ['["gateway-prd-us-east1-b-v7b4",{"micros":3796,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":3585,"calls":[]},"session_lookup_finished",{"micros":17,"calls":[]},"discord-sessions-prd-1-238",{"micros":27}]}]']}}
2024-12-16 21:09:54,075:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 21:09:54,075:INFO:discord.gateway: Shard ID None has successfully RESUMED session 0c6a1229d4a1df0c481b5ac6d8933406.
2024-12-16 21:09:54,075:DEBUG:discord.client: Dispatching event resumed
2024-12-16 21:10:08,514:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
2024-12-16 21:10:08,520:DEBUG:discord.gateway: Websocket closed with 1006, attempting a reconnect.
2024-12-16 21:10:08,521:DEBUG:discord.client: Got a request to RESUME the websocket.
2024-12-16 21:10:08,521:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:10:08,618:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:10:08,619:ERROR:discord.client: Attempting a reconnect in 8.60s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:10:17,237:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:10:17,237:ERROR:discord.client: Attempting a reconnect in 4.60s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:10:21,856:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:10:21,856:ERROR:discord.client: Attempting a reconnect in 100.62s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:12:02,506:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:12:02,506:ERROR:discord.client: Attempting a reconnect in 85.86s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:13:28,386:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:13:28,386:ERROR:discord.client: Attempting a reconnect in 224.76s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:17:13,173:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:17:13,173:ERROR:discord.client: Attempting a reconnect in 41.77s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:17:54,959:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:17:54,959:ERROR:discord.client: Attempting a reconnect in 550.37s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:27:05,347:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:27:05,347:ERROR:discord.client: Attempting a reconnect in 717.37s
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 900, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-12-16 21:39:03,059:DEBUG:discord.gateway: Created websocket connected to wss://gateway-us-east1-b.discord.gg
2024-12-16 21:39:03,063:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-50mj",{"micros":0.0}]']}}
2024-12-16 21:39:03,068:DEBUG:discord.gateway: Shard ID None has sent the RESUME payload.
2024-12-16 21:39:03,315:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:39:03,315:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 9, 'd': False}
2024-12-16 21:39:03,315:INFO:discord.gateway: Shard ID None session has been invalidated.
2024-12-16 21:39:03,633:DEBUG:discord.client: Got a request to IDENTIFY the websocket.
2024-12-16 21:39:03,633:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 21:39:04,033:DEBUG:discord.gateway: Created websocket connected to wss://gateway-us-east1-b.discord.gg
2024-12-16 21:39:04,033:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-jj18",{"micros":0.0}]']}}
2024-12-16 21:39:09,045:DEBUG:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-12-16 21:39:09,045:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:39:09,357:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'READY', 's': 1, 'op': 0, 'd': {'v': 10, 'user_settings': {}, 'user': {'verified': True, 'username': '봇물', 'primary_guild': None, 'mfa_enabled': False, 'id': '1318114372438196328', 'global_name': None, 'flags': 0, 'email': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'session_type': 'normal', 'session_id': '80a872745ed1e444d9e4e504a38e96ca', 'resume_gateway_url': 'wss://gateway-us-east1-b.discord.gg', 'relationships': [], 'private_channels': [], 'presences': [], 'guilds': [{'unavailable': True, 'id': '1195620522294247494'}], 'guild_join_requests': [], 'geo_ordered_rtc_regions': ['south-korea', 'japan', 'hongkong', 'singapore', 'india'], 'game_relationships': [], 'auth': {}, 'application': {'id': '1318114372438196328', 'flags': 565248}, '_trace': ['["gateway-prd-us-east1-b-jj18",{"micros":60383,"calls":["id_created",{"micros":767,"calls":[]},"session_lookup_time",{"micros":258,"calls":[]},"session_lookup_finished",{"micros":12,"calls":[]},"discord-sessions-prd-1-196",{"micros":57991,"calls":["start_session",{"micros":46070,"calls":["discord-api-rpc-fbd795bc-wphvs",{"micros":41511,"calls":["get_user",{"micros":12081},"get_guilds",{"micros":5070},"send_scheduled_deletion_message",{"micros":9},"guild_join_requests",{"micros":1},"authorized_ip_coro",{"micros":8}]}]},"starting_guild_connect",{"micros":74,"calls":[]},"presence_started",{"micros":11440,"calls":[]},"guilds_started",{"micros":84,"calls":[]},"lobbies_started",{"micros":1,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":279,"calls":[]},"connect_finished",{"micros":283,"calls":[]},"build_ready",{"micros":17,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":19,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']}}
2024-12-16 21:39:09,357:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 21:39:09,357:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 80a872745ed1e444d9e4e504a38e96ca).
2024-12-16 21:39:09,363:DEBUG:discord.client: Dispatching event connect
2024-12-16 21:39:09,367:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'activity_instances': [], 'region': 'deprecated', 'discovery_splash': None, 'nsfw': False, 'member_count': 25, 'preferred_locale': 'ko', 'roles': [{'version': 1733375534712, 'unicode_emoji': None, 'tags': {}, 'position': 0, 'permissions': '2222085186767425', 'name': '@everyone', 'mentionable': False, 'managed': False, 'id': '1195620522294247494', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834611, 'unicode_emoji': None, 'tags': {}, 'position': 5, 'permissions': '8', 'name': '서버 관리자', 'mentionable': False, 'managed': False, 'id': '1195622998825242694', 'icon': None, 'hoist': False, 'flags': 0, 'color': 3447003}, {'version': 1733375617678, 'unicode_emoji': None, 'tags': {}, 'position': 3, 'permissions': '1024', 'name': 'GSM', 'mentionable': False, 'managed': False, 'id': '1195623696895852564', 'icon': None, 'hoist': False, 'flags': 0, 'color': 7602064}, {'version': 1731652834623, 'unicode_emoji': None, 'tags': {'bot_id': '159985870458322944'}, 'position': 10, 'permissions': '364870364383', 'name': 'MEE6', 'mentionable': False, 'managed': True, 'id': '1195629722185506940', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834609, 'unicode_emoji': None, 'tags': {}, 'position': 4, 'permissions': '8', 'name': '봇', 'mentionable': False, 'managed': False, 'id': '1195629770281582602', 'icon': None, 'hoist': True, 'flags': 0, 'color': 5896959}, {'version': 1731652834619, 'unicode_emoji': None, 'tags': {'bot_id': '513423712582762502'}, 'position': 8, 'permissions': '36719617', 'name': 'TTS Bot!', 'mentionable': False, 'managed': True, 'id': '1195632271760302105', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834617, 'unicode_emoji': None, 'tags': {'bot_id': '479108435984515072'}, 'position': 7, 'permissions': '431689690192', 'name': '노래하는 하리보', 'mentionable': False, 'managed': True, 'id': '1195635742307786814', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834613, 'unicode_emoji': None, 'tags': {'bot_id': '896270994740764684'}, 'position': 6, 'permissions': '281357446256', 'name': '뽀삐', 'mentionable': False, 'managed': True, 'id': '1195638311868444835', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731652834621, 'unicode_emoji': None, 'tags': {'bot_id': '155149108183695360'}, 'position': 9, 'permissions': '1513962695871', 'name': 'Dyno', 'mentionable': False, 'managed': True, 'id': '1195638871187275878', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}, {'version': 1731761636512, 'unicode_emoji': None, 'tags': {'premium_subscriber': None}, 'position': 1, 'permissions': '2221707229646401', 'name': '흑우', 'mentionable': False, 'managed': True, 'id': '1257989377561460839', 'icon': None, 'hoist': False, 'flags': 0, 'color': 16023551}, {'version': 1731761625458, 'unicode_emoji': None, 'tags': {}, 'position': 2, 'permissions': '0', 'name': '범죄자', 'mentionable': False, 'managed': False, 'id': '1306871368276770908', 'icon': None, 'hoist': False, 'flags': 0, 'color': 16711680}, {'version': 1734333557995, 'unicode_emoji': None, 'tags': {'bot_id': '1318114372438196328'}, 'position': 1, 'permissions': '8', 'name': '8G4B-bot', 'mentionable': False, 'managed': True, 'id': '1318115220325138445', 'icon': None, 'hoist': False, 'flags': 0, 'color': 0}], 'incidents_data': {'raid_detected_at': '2024-12-05T05:14:55.709010+00:00', 'invites_disabled_until': None, 'dms_disabled_until': None, 'dm_spam_detected_at': None}, 'lazy': True, 'presences': [], 'large': False, 'clan': None, 'mfa_level': 0, 'max_members': 500000, 'id': '1195620522294247494', 'afk_channel_id': '1195622458816987146', 'verification_level': 1, 'name': '최강', 'premium_tier': 0, 'owner_id': '846325069994000424', 'rules_channel_id': '1195620849781317743', 'system_channel_flags': 15, 'max_video_channel_users': 25, 'unavailable': False, 'threads': [{'type': 11, 'total_message_sent': 8, 'thread_metadata': {'locked': False, 'create_timestamp': '2024-11-28T03:03:18.472960+00:00', 'auto_archive_duration': 4320, 'archived': False, 'archive_timestamp': '2024-11-28T03:03:18.472960+00:00'}, 'rate_limit_per_user': 0, 'parent_id': '1195621469682683944', 'owner_id': '846325069994000424', 'name': 'ucc 조별로 치킨(양념, 후라이드), 피자종류 골라서 팀 대표가 올려', 'message_count': 7, 'member_count': 1, 'last_message_id': '1311534784518033529', 'id': '1311527458998059050', 'guild_id': '1195620522294247494', 'flags': 0}, {'type': 11, 'total_message_sent': 18, 'thread_metadata': {'locked': False, 'create_timestamp': '2024-12-06T06:31:37.411910+00:00', 'auto_archive_duration': 4320, 'archived': False, 'archive_timestamp': '2024-12-06T06:31:37.411910+00:00'}, 'rate_limit_per_user': 0, 'parent_id': '1195640167982190592', 'owner_id': '846325069994000424', 'name': '스타 박아**줘** (스레드 열어주세요) @준준', 'message_count': 18, 'member_count': 10, 'last_message_id': '1315632819950583958', 'id': '1314479239403409478', 'guild_id': '1195620522294247494', 'flags': 0}], 'icon': 'a57fb06f70c17a29e5822f08229f24da', 'system_channel_id': '1195620692620750848', 'afk_timeout': 1800, 'max_stage_video_channel_users': 50, 'premium_progress_bar_enabled': False, 'description': None, 'nsfw_level': 0, 'channels': [{'version': 1710736814791, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '2048', 'allow': '0'}], 'parent_id': '1195639935630311484', 'nsfw': False, 'name': '😀ㅣ어서와', 'last_message_id': '1318115221361004557', 'id': '1195620692620750848', 'flags': 0}, {'version': 1705133194366, 'type': 4, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'name': '공지', 'id': '1195620749151584336', 'flags': 0}, {'version': 1710736822028, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'parent_id': '1195620749151584336', 'nsfw': False, 'name': '📌ㅣ고정공지', 'last_message_id': '1195643981229465650', 'id': '1195620849781317743', 'flags': 0}, {'version': 1710736829169, 'type': 5, 'topic': '', 'rate_limit_per_user': 0, 'position': 2, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '377957173248', 'allow': '0'}], 'parent_id': '1195620749151584336', 'nsfw': False, 'name': '📢ㅣ공지사항', 'last_message_id': '1266040161586647222', 'id': '1195620925589164032', 'flags': 0}, {'version': 1705133194375, 'type': 4, 'position': 2, 'permission_overwrites': [], 'name': '명령어', 'id': '1195621021991059507', 'flags': 0}, {'version': 1710736841958, 'type': 0, 'topic': '원하는 노래의 제목만 입력하면 됩니다.', 'rate_limit_per_user': 0, 'position': 4, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🐶ㅣ뽀삐', 'last_message_id': '1260524443751551056', 'id': '1195621251901829120', 'flags': 0}, {'version': 1710736847674, 'type': 0, 'topic': '마이크 못 쓰는 친구들을 위한 TTS봇', 'rate_limit_per_user': 0, 'position': 5, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🎤ㅣtts', 'last_pin_timestamp': '2024-01-13T07:48:44+00:00', 'last_message_id': '1308177657728466985', 'id': '1195621288891383808', 'flags': 0}, {'version': 1705133194388, 'type': 4, 'position': 3, 'permission_overwrites': [], 'name': '소통', 'id': '1195621329240600576', 'flags': 0}, {'version': 1710736854381, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 6, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '💬ㅣ전체채팅', 'last_pin_timestamp': '2024-11-28T03:25:41+00:00', 'last_message_id': '1318179611225493544', 'id': '1195621469682683944', 'flags': 0}, {'version': 1710736868656, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 8, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📚ㅣ정보공유', 'last_pin_timestamp': '2024-01-13T08:26:13+00:00', 'last_message_id': '1315890412485087282', 'id': '1195621924445896745', 'flags': 0}, {'version': 1722982677867, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '🔊ㅣ전체보이스', 'last_message_id': '1284874571228381386', 'id': '1195622348494221384', 'flags': 0, 'bitrate': 96000}, {'version': 1710736906253, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '🔊ㅣ수다떨기', 'last_message_id': '1244781625531830343', 'id': '1195622422745993257', 'flags': 0, 'bitrate': 64000}, {'version': 1705303052774, 'user_limit': 0, 'type': 2, 'status': None, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 2, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'name': '😴ㆍ잠수방', 'last_message_id': '1244781627175866388', 'id': '1195622458816987146', 'flags': 0, 'bitrate': 64000}, {'version': 1705133194403, 'type': 4, 'position': 4, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'name': '서버관리', 'id': '1195624790858408048', 'flags': 0}, {'version': 1710737189370, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 12, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'parent_id': '1195624790858408048', 'nsfw': False, 'name': '💾ㅣ채팅로그', 'last_message_id': '1318182525553606728', 'id': '1195624958257266749', 'flags': 0}, {'version': 1710737182373, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 11, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '1049600', 'allow': '0'}], 'parent_id': '1195624790858408048', 'nsfw': False, 'name': '💻ㅣ관리자', 'last_message_id': '1314097655248322593', 'id': '1195625084883325069', 'flags': 0}, {'version': 1710736835389, 'type': 0, 'topic': '⏹ - 재생을 멈추고, 대기열을 초기화해요.\n🔁 - 반복 모드를 변경해요.\n🔀 - 대기열에 있는 트랙을 섞어요.\n⏭ - 재생 중인 노래를 스킵해요.\n⏯ - 곡을 일시정지하거나 재생해요.', 'rate_limit_per_user': 0, 'position': 3, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '🍭ㅣ하리보', 'last_pin_timestamp': '2024-01-13T07:57:56+00:00', 'last_message_id': '1260524456988639243', 'id': '1195637508709568562', 'flags': 0}, {'version': 1705134571662, 'type': 4, 'position': 0, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '2048', 'allow': '0'}], 'name': '환영', 'id': '1195639935630311484', 'flags': 0}, {'version': 1710736883090, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 10, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📬ㅣ건의함', 'last_pin_timestamp': '2024-01-13T08:07:51+00:00', 'last_message_id': '1314489183741542411', 'id': '1195640167982190592', 'flags': 0}, {'version': 1710736862476, 'type': 0, 'topic': '', 'rate_limit_per_user': 0, 'position': 7, 'permission_overwrites': [], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '📷ㅣ짤방', 'last_pin_timestamp': '2024-01-23T00:47:05+00:00', 'last_message_id': '1318171183400747110', 'id': '1199152735480713267', 'flags': 0}, {'version': 1725002828909, 'type': 15, 'topic': '||궁금한 것들이 있다면 이곳에||', 'theme_color': None, 'template': '', 'rate_limit_per_user': 10, 'position': 9, 'permission_overwrites': [{'type': 0, 'id': '1195620522294247494', 'deny': '0', 'allow': '65536'}], 'parent_id': '1195621329240600576', 'nsfw': False, 'name': '❓ㅣ질문방', 'last_message_id': '1301509790693851136', 'id': '1199156871869775923', 'icon_emoji': None, 'flags': 16, 'default_sort_order': None, 'default_reaction_emoji': {'emoji_name': '👍', 'emoji_id': None}, 'default_forum_layout': 1, 'available_tags': [{'name': '해결필요', 'moderated': False, 'id': '1199157208353615893', 'emoji_name': '✏️', 'emoji_id': None}, {'name': '해결완료', 'moderated': False, 'id': '1199157313370599485', 'emoji_name': '✅', 'emoji_id': None}, {'name': '해결불가', 'moderated': False, 'id': '1199157362422988821', 'emoji_name': '❌', 'emoji_id': None}]}, {'version': 1734338701781, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 13, 'permission_overwrites': [], 'parent_id': '1195621021991059507', 'nsfw': False, 'name': '💧ㅣ봇물', 'last_message_id': '1318182523980877834', 'id': '1318136795229061120', 'flags': 0}], 'premium_subscription_count': 0, 'inventory_settings': None, 'application_id': None, 'stage_instances': [], 'safety_alerts_channel_id': '1195625084883325069', 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'embedded_activities': [], 'vanity_url_code': None, 'soundboard_sounds': [], 'banner': None, 'public_updates_channel_id': '1195625084883325069', 'members': [{'user': {'username': '봇물', 'public_flags': 0, 'id': '1318114372438196328', 'global_name': None, 'display_name': None, 'discriminator': '8623', 'clan': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '9ff8c4ee21b38b9f40f4169489ad4104'}, 'roles': ['1195629770281582602', '1318115220325138445'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2024-12-16T07:19:18.005000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}], 'explicit_content_filter': 2, 'default_message_notifications': 1, 'hub_type': None, 'latest_onboarding_question_id': None, 'guild_scheduled_events': [], 'voice_states': [], 'version': 1733375695710, 'splash': None, 'features': ['COMMUNITY', 'SOUNDBOARD', 'NEWS'], 'emojis': [], 'stickers': [{'version': 1705299422099, 'type': 2, 'tags': '🏫', 'name': 'GSM', 'id': '1196337228293603348', 'guild_id': '1195620522294247494', 'format_type': 1, 'description': '', 'available': True, 'asset': ''}], 'application_command_counts': {}, 'home_header': None}}
2024-12-16 21:39:09,383:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 21:39:09,383:DEBUG:discord.client: Dispatching event guild_available
2024-12-16 21:39:11,398:DEBUG:discord.client: Dispatching event ready
2024-12-16 21:39:45,288:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:39:45,643:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:40:26,548:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:40:26,775:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:41:07,804:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:41:08,023:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:41:49,066:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:41:49,273:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:42:30,322:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:42:30,616:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:43:11,581:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:43:11,842:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:43:52,839:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:43:53,052:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:44:34,096:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:44:34,377:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:45:15,351:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:45:15,557:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:45:56,611:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:45:56,951:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:46:37,864:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:46:38,071:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:47:19,123:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:47:19,324:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:48:00,388:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:48:00,611:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:48:41,641:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:48:41,885:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:49:22,897:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:49:23,104:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:50:04,154:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:50:04,364:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:50:45,407:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:50:45,757:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:51:26,670:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:51:26,987:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:52:07,926:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:52:08,240:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:52:49,194:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:52:49,483:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:53:30,461:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:53:30,750:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:54:11,727:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:54:12,023:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:54:52,988:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:54:53,328:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:55:34,249:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:55:34,604:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:56:15,506:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:56:15,824:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:56:56,766:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:56:57,051:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:57:38,026:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:57:38,384:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:58:19,286:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:58:19,520:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:59:00,546:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:59:00,748:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 21:59:41,808:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 21:59:42,014:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:00:23,066:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:00:23,321:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:01:04,319:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:01:04,525:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:01:45,597:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:01:45,858:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:02:26,857:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:02:27,122:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:03:08,118:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:03:08,328:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:03:49,375:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:03:49,587:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:04:30,630:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:04:30,931:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:05:11,886:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:05:12,108:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:05:53,139:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:05:53,366:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:06:34,394:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 2.
2024-12-16 22:06:34,626:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:06:46,925:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 7, 'd': None}
2024-12-16 22:06:46,925:DEBUG:discord.gateway: Received RECONNECT opcode.
2024-12-16 22:06:47,126:DEBUG:discord.client: Got a request to RESUME the websocket.
2024-12-16 22:06:47,126:DEBUG:discord.client: Dispatching event disconnect
2024-12-16 22:06:47,528:DEBUG:discord.gateway: Created websocket connected to wss://gateway-us-east1-b.discord.gg
2024-12-16 22:06:47,530:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-us-east1-b-b2mm",{"micros":0.0}]']}}
2024-12-16 22:06:47,530:DEBUG:discord.gateway: Shard ID None has sent the RESUME payload.
2024-12-16 22:06:47,845:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:06:47,846:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'RESUMED', 's': 3, 'op': 0, 'd': {'_trace': ['["gateway-prd-us-east1-b-b2mm",{"micros":3241,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":3012,"calls":[]},"session_lookup_finished",{"micros":12,"calls":[]},"discord-sessions-prd-1-196",{"micros":20}]}]']}}
2024-12-16 22:06:47,846:DEBUG:discord.client: Dispatching event socket_event_type
2024-12-16 22:06:47,846:INFO:discord.gateway: Shard ID None has successfully RESUMED session 80a872745ed1e444d9e4e504a38e96ca.
2024-12-16 22:06:47,846:DEBUG:discord.client: Dispatching event resumed
2024-12-16 22:07:28,782:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:07:28,997:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:08:10,043:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:08:10,265:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:08:51,296:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:08:51,539:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:09:32,555:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:09:32,805:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:10:13,815:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:10:14,055:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:10:55,067:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:10:55,283:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:11:36,329:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:11:36,534:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:12:17,587:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:12:17,789:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:12:58,850:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:12:59,141:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:13:40,108:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:13:40,348:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:14:21,376:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:14:21,589:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:15:02,635:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:15:02,943:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:15:43,892:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:15:44,211:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:16:25,151:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:16:25,488:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:17:06,411:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:17:06,633:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:17:47,667:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:17:47,885:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:18:28,923:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:18:29,184:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:19:10,178:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:19:10,442:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:19:51,433:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:19:51,719:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
2024-12-16 22:20:32,697:DEBUG:discord.gateway: Keeping shard ID None websocket alive with sequence 3.
2024-12-16 22:20:32,980:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
